.word   handle_fx_stop
.word   handle_fx_nop
.word   handle_fx_cache
.word   handle_fx_lsr
.word   handle_fx_rol
.word   handle_fx_bra
.word   handle_fx_bge
.word   handle_fx_blt
.word   handle_fx_bne
.word   handle_fx_beq
.word   handle_fx_bpl
.word   handle_fx_bmi
.word   handle_fx_bcc
.word   handle_fx_bcs
.word   handle_fx_bvc
.word   handle_fx_bvs
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r14
.word   handle_fx_to_r15
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_loop
.word   handle_fx_alt1
.word   handle_fx_alt2
.word   handle_fx_alt3
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_plot_2bit
.word   handle_fx_swap
.word   handle_fx_color
.word   handle_fx_not
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_add_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_sub_r
.word   handle_fx_merge
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_and_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_mult_r
.word   handle_fx_sbk
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_sex
.word   handle_fx_asr
.word   handle_fx_ror
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_lob
.word   handle_fx_fmult
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r
.word   handle_fx_ibt_r14
.word   handle_fx_ibt_r15
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_hib
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_or_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r14
.word   handle_fx_getc
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r14
.word   handle_fx_getb
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r
.word   handle_fx_iwt_r14
.word   handle_fx_iwt_r15
.word   handle_fx_stop
.word   handle_fx_nop
.word   handle_fx_cache
.word   handle_fx_lsr
.word   handle_fx_rol
.word   handle_fx_bra
.word   handle_fx_bge
.word   handle_fx_blt
.word   handle_fx_bne
.word   handle_fx_beq
.word   handle_fx_bpl
.word   handle_fx_bmi
.word   handle_fx_bcc
.word   handle_fx_bcs
.word   handle_fx_bvc
.word   handle_fx_bvs
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r14
.word   handle_fx_to_r15
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_loop
.word   handle_fx_alt1
.word   handle_fx_alt2
.word   handle_fx_alt3
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_rpix_2bit
.word   handle_fx_swap
.word   handle_fx_cmode
.word   handle_fx_not
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_adc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_sbc_r
.word   handle_fx_merge
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_bic_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_umult_r
.word   handle_fx_sbk
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_sex
.word   handle_fx_div2
.word   handle_fx_ror
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_lob
.word   handle_fx_lmult
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r14
.word   handle_fx_lms_r15
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_hib
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_xor_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r14
.word   handle_fx_getc
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r14
.word   handle_fx_getbh
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r14
.word   handle_fx_lm_r15
.word   handle_fx_stop
.word   handle_fx_nop
.word   handle_fx_cache
.word   handle_fx_lsr
.word   handle_fx_rol
.word   handle_fx_bra
.word   handle_fx_bge
.word   handle_fx_blt
.word   handle_fx_bne
.word   handle_fx_beq
.word   handle_fx_bpl
.word   handle_fx_bmi
.word   handle_fx_bcc
.word   handle_fx_bcs
.word   handle_fx_bvc
.word   handle_fx_bvs
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r14
.word   handle_fx_to_r15
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_stw_r
.word   handle_fx_loop
.word   handle_fx_alt1
.word   handle_fx_alt2
.word   handle_fx_alt3
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_ldw_r
.word   handle_fx_plot_2bit
.word   handle_fx_swap
.word   handle_fx_color
.word   handle_fx_not
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_add_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_sub_i
.word   handle_fx_merge
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_and_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_mult_i
.word   handle_fx_sbk
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_sex
.word   handle_fx_asr
.word   handle_fx_ror
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_jmp_r
.word   handle_fx_lob
.word   handle_fx_fmult
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_sms_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_hib
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_or_i
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r14
.word   handle_fx_ramb
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r14
.word   handle_fx_getbl
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_sm_r
.word   handle_fx_stop
.word   handle_fx_nop
.word   handle_fx_cache
.word   handle_fx_lsr
.word   handle_fx_rol
.word   handle_fx_bra
.word   handle_fx_bge
.word   handle_fx_blt
.word   handle_fx_bne
.word   handle_fx_beq
.word   handle_fx_bpl
.word   handle_fx_bmi
.word   handle_fx_bcc
.word   handle_fx_bcs
.word   handle_fx_bvc
.word   handle_fx_bvs
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r
.word   handle_fx_to_r14
.word   handle_fx_to_r15
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_with_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_stb_r
.word   handle_fx_loop
.word   handle_fx_alt1
.word   handle_fx_alt2
.word   handle_fx_alt3
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_ldb_r
.word   handle_fx_rpix_2bit
.word   handle_fx_swap
.word   handle_fx_cmode
.word   handle_fx_not
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_adc_i
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_cmp_r
.word   handle_fx_merge
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_bic_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_umult_i
.word   handle_fx_sbk
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_link_i
.word   handle_fx_sex
.word   handle_fx_div2
.word   handle_fx_ror
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_ljmp_r
.word   handle_fx_lob
.word   handle_fx_lmult
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r
.word   handle_fx_lms_r14
.word   handle_fx_lms_r15
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_from_r
.word   handle_fx_hib
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_xor_i
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r
.word   handle_fx_inc_r14
.word   handle_fx_romb
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r
.word   handle_fx_dec_r14
.word   handle_fx_getbs
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r
.word   handle_fx_lm_r14
.word   handle_fx_lm_r15
